import {
  faCcVisa,
  faInstagram,
  faTwitter,
} from "@fortawesome/free-brands-svg-icons";
import {
  fa0,
  fa1,
  fa2,
  fa3,
  fa4,
  fa5,
  fa6,
  fa7,
  fa8,
  fa9,
  faBars,
  faBullseye,
  faCalendarAlt,
  faCalendarDay,
  faCheckCircle,
  faCircle,
  faCircleChevronLeft,
  faCircleChevronRight,
  faCircleDot,
  faCircleNotch,
  faEnvelope,
  faGamepad,
  faGlobe,
  faHands,
  faHandSpock,
  faHeart,
  faHome,
  faImage,
  faInfo,
  faLeftLong,
  faListCheck,
  faMoneyBill,
  faPaperPlane,
  faRefresh,
  faRightLong,
  faSave,
  faShoePrints,
  faShoppingCart,
  faSpinner,
  faSquareCheck,
  faStore,
  faUpLong,
  faUsd,
  faUser,
  faX,
} from "@fortawesome/free-solid-svg-icons";
import { IconDefinition } from "@fortawesome/fontawesome-svg-core";

/**
 * TODO: enum icons to preven null or undefiened errors
 */
// enum IconNames {
//   home = "home",
//   about = "about",
//   services = "services",
//   booking = "booking",
//   accessories = "accessories",
//   contact = "contact",
//   checkout = "checkout",
//   pricing = "pricing",
//   check = "check",
//   uncheck = "uncheck",
//   submit = "submit",
//   dashboard = "dashboard",
//   login = "login",
//   burger = "burger",
//   instagram = "instagram",
//   twitter = "twitter",
//   wig = "wig",
//   braids = "braids",
//   nail = "nail",
//   all = "all",
//   manicure = "manicure",
//   pedicure = "pedicure",
//   promotion = "promotion",
//   schedule = "schedule",
//   today = "today",
//   booked = "booked",
//   appointments = "appointments",
//   left = "left",
//   right = "right",
//   prev = "prev",
//   next = "next",
//   first = "first",
//   last = "last",
//   top = "top",
//   spinner = "spinner",
//   loading = "loading",
//   circle = "circle",
//   store = "store",
//   debit = "debit",
//   credit = "credit",
//   visa = "visa",
//   cashapp = "cashapp",
//   heart = "heart",
//   save = "save",
//   x = "x",
//   refresh = "refresh",
//   games = "games",
//   dot = "dot",
//   one = "1",
//   two = "2",
//   three = "3",
//   four = "4",
//   five = "5",
//   six = "6",
//   seven = "7",
//   eight = "8",
//   nine = "9",
// }
// enum Icons {
//   faHome,
//   faInfo,
//   faListCheck,
//   faImage,
//   faEnvelope,
//   faShoppingCart,
//   faUsd,
//   faCheckCircle,
//   faCircle,
//   faPaperPlane,
//   faBars,
//   faInstagram,
//   faTwitter,
//   faUser,
//   faHandSpock,
//   faGlobe,
//   faHands,
//   faShoePrints,
//   faBullseye,
//   faCalendarAlt,
//   faCalendarDay,
//   faSquareCheck,
//   faCircleChevronLeft,
//   faCircleChevronRight,
//   faUpLong,
//   faSpinner,
//   faCircleNotch,
//   faStore,
//   faCcVisa,
//   faMoneyBill,
//   faHeart,
//   faSave,
//   faX,
//   faRefresh,
//   faGamepad,
//   faCircleDot,
//   fa1,
//   fa2,
//   fa3,
//   fa4,
//   fa5,
//   fa6,
//   fa7,
//   fa8,
//   fa9,
//   fa0,
// }

interface KeyDefinition {
  [key: string]: IconDefinition;
}
export const svg: KeyDefinition = {
  home: faHome,
  about: faInfo,
  services: faListCheck,
  booking: faCalendarAlt,
  accessories: faImage,
  contact: faEnvelope,
  checkout: faShoppingCart,
  pricing: faUsd,
  check: faCheckCircle,
  uncheck: faCircle,
  submit: faPaperPlane,
  dashboard: faUser,
  login: faUser,
  burger: faBars,
  instagram: faInstagram,
  twitter: faTwitter,
  wig: faUser,
  braids: faUser,
  nail: faHandSpock,
  all: faGlobe,
  manicure: faHands,
  pedicure: faShoePrints,
  promotion: faBullseye,
  schedule: faCalendarAlt,
  today: faCalendarDay,
  booked: faSquareCheck,
  appointments: faSquareCheck,
  left: faLeftLong,
  right: faRightLong,
  prev: faLeftLong,
  next: faRightLong,
  first: faCircleChevronLeft,
  last: faCircleChevronRight,
  top: faUpLong,
  spinner: faSpinner,
  loading: faSpinner,
  circle: faCircleNotch,
  store: faStore,
  visa: faCcVisa,
  cashapp: faMoneyBill,
  heart: faHeart,
  save: faSave,
  x: faX,
  refresh: faRefresh,
  games: faGamepad,
  dot: faCircleDot,
  1: fa1,
  2: fa2,
  3: fa3,
  4: fa4,
  5: fa5,
  6: fa6,
  7: fa7,
  8: fa8,
  9: fa9,
  0: fa0,
};
export const getDefinition = (name: string) => {
  return svg[name];
};
