export const placeholders: { [key: string]: string } = {
  firstName: "Peter ..",
  lastName: "Griffin ..",
  name: "enter your name ..",
  streetAddress: "123 Street..",
  email: "email@example.com",
  apt: "1234",
  city: "Narnia ..",
  state: "State ..",
  postalCode: "56789",
  phone: "987-654-3210",
  username: "Enter username ..",
  password: "Enter password ..",
  oldPassword: "Enter old password",
  newPassword: "Enter new password",
  confirmPassword: "Confirm matching password ..",
  confirmNewPassword: "Confirm new password must match new password ..",
  search: "search ..",
};
