export const placeholders: { [key: string]: string } = {
  firstName: "Peter..",
  lastName: "Griffin..",
  name: "Enter name",
  streetAddress: "123 Street..",
  email: "email@example.com",
  apt: "1234",
  city: "Narnia ..",
  state: "State..",
  postalCode: "56789",
  phone: "987-654-3210",
  username: "",
  password: "",
  confirmPassword: "",
  search: "Search..",
};
