import {
  faCcMastercard,
  faCcVisa,
  faFacebook,
  faInstagram,
  faPaypal,
  faTwitter,
} from "@fortawesome/free-brands-svg-icons";
import {
  fa0,
  fa1,
  fa2,
  fa3,
  fa4,
  fa5,
  fa6,
  fa7,
  fa8,
  fa9,
  faBars,
  faBullseye,
  faCalendarAlt,
  faCalendarDay,
  faCheckCircle,
  faCircle,
  faCircleChevronLeft,
  faCircleChevronRight,
  faCircleDot,
  faCircleNotch,
  faEnvelope,
  faGamepad,
  faGlobe,
  faHands,
  faHandSpock,
  faHeart,
  faHome,
  faImage,
  faInfo,
  faLeftLong,
  faListCheck,
  faLock,
  // faMagnifyingGlass,
  // faMagnifyingGlassArrowRight,
  // faMagnifyingGlassChart,
  // faMagnifyingGlassDollar,
  // faMagnifyingGlassLocation,
  // faMagnifyingGlassMinus,
  // faMagnifyingGlassPlus,
  faMoneyBill,
  faPaperPlane,
  faQuestion,
  // faReceipt,
  faRefresh,
  faRightLong,
  faSave,
  faShoePrints,
  faShoppingCart,
  faSpinner,
  faSquareCheck,
  faStar,
  faStore,
  faUpLong,
  faUsd,
  faUser,
  faX,
} from "@fortawesome/free-solid-svg-icons";
import { library } from "@fortawesome/fontawesome-svg-core";
import { IconDefinition } from "@fortawesome/free-brands-svg-icons";
type SVGProp = {
  [key: string]: IconDefinition;
};
const svg: SVGProp = {
  about: faInfo,
  accessories: faImage,
  all: faGlobe,
  appointments: faSquareCheck,
  booking: faCalendarAlt,
  user: faUser,
  booked: faSquareCheck,
  burger: faBars,
  cashapp: faMoneyBill,
  check: faCheckCircle,
  checkout: faShoppingCart,
  contact: faEnvelope,
  circle: faCircleNotch,
  dot: faCircleDot,
  dashboard: faUser,
  flag: faGlobe,
  FAQ: faQuestion,
  facebook: faFacebook,
  first: faCircleChevronLeft,
  games: faGamepad,
  heart: faHeart,
  home: faHome,
  instagram: faInstagram,
  left: faLeftLong,
  manicure: faHands,
  mastercard: faCcMastercard,
  paypal: faPaypal,
  pedicure: faShoePrints,
  promotion: faBullseye,
  pricing: faUsd,
  prev: faLeftLong,
  nail: faHandSpock,
  loading: faSpinner,
  login: faUser,
  submit: faPaperPlane,
  save: faSave,
  star: faStar,
  schedule: faCalendarAlt,
  services: faListCheck,
  secure: faLock,
  spinner: faSpinner,
  store: faStore,
  today: faCalendarDay,
  testimonials: faBullseye,
  // testimonials: faReceipt,
  // testimonials: faMagnifyingGlassArrowRight,
  // testimonials: faMagnifyingGlassChart,
  // testimonials: faMagnifyingGlassDollar,
  // testimonials: faMagnifyingGlassLocation,
  // testimonials: faMagnifyingGlassMinus,
  // testimonials: faMagnifyingGlassPlus,
  twitter: faTwitter,
  top: faUpLong,
  uncheck: faCircle,
  right: faRightLong,
  refresh: faRefresh,
  next: faRightLong,
  last: faCircleChevronRight,
  visa: faCcVisa,
  wig: faUser,
  x: faX,
  one: fa1,
  two: fa2,
  three: fa3,
  four: fa4,
  five: fa5,
  six: fa6,
  seven: fa7,
  eight: fa8,
  nine: fa9,
  zero: fa0,
};
library.add(svg);
export { svg };
